# TASK
- create arrays with all the data types available in numpy
    * integer - i
    * boolean - b
    * unsigned integer - u
    * float - f
    * complex float - c
    * timedelta - m
    * datatime - M
    * object - O
    * string - S
    * unicode string - U
    * fixed chunk of memory for other type (void) - V

In [2]:
import numpy as np

In [3]:
a = np.array([11,12,13,14,15])   #integer
print(a)
a.dtype

[11 12 13 14 15]


dtype('int32')

In [5]:
a = np.array([11,12,13,14,15] ,dtype= 'bool')  #boolean
print(a)
a.dtype

[ True  True  True  True  True]


dtype('bool')

In [8]:
a = np.array([-11,-12,13,14,15] ,dtype= 'uint16') #unsigned integer 
print(a)
a.dtype

[65525 65524    13    14    15]


dtype('uint16')

In [11]:
a= np.array([12,442,33.33,7.8,9.67])   #float
print(a)
a.dtype

[ 12.   442.    33.33   7.8    9.67]


dtype('float64')

In [12]:
a = np.array([10.4,1 + 12j,90.38j])  #complex float
print(a)
a.dtype

[10.4 +0.j    1. +12.j    0. +90.38j]


dtype('complex128')

In [16]:
a=np.timedelta64(5, 'Y')   #timedelta
print(a)

5 years


In [13]:
a=np.timedelta64(5, 'M')   #timedelta
print(a)

5 months


In [14]:
a=np.array(['2021-06-21', '2006-01-15', '2001-10-05'], dtype='datetime64')   #datetime
a

array(['2021-06-21', '2006-01-15', '2001-10-05'], dtype='datetime64[D]')

In [15]:
a = np.array([55,45,35], dtype='O')  #object
a

array([55, 45, 35], dtype=object)

In [17]:
a = np.array(['Likhitha', 'APSSDC', 'Internship'])  #String
print(a)
a.dtype

['Likhitha' 'APSSDC' 'Internship']


dtype('<U10')

In [31]:
a = np.array([u'\u0065',u'\u2202r',u'\u1F601'], dtype='U')  #unicode string
a

array(['e', '∂r', 'ὠ1'], dtype='<U2')

In [32]:
a=np.void([], dtype='V')  #void
a

array([], dtype='|V8')